In [1]:
import numpy as np

# 1. Creating arrays
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

# 2. Arrays with zeros, ones, random values
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3))
rand_arr = np.random.rand(2, 3)

print("Zeros Array:\n", zeros_arr)
print("Ones Array:\n", ones_arr)
print("Random Array:\n", rand_arr)

# 3. Basic operations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square Root:", np.sqrt(a))

# 4. Broadcasting
print("Broadcasting Example:", a + 5)

# 5. Statistical operations
print("Mean:", np.mean(a))
print("Sum:", np.sum(a))

# 6. Dot product (matrix multiplication)
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("Dot Product:\n", np.dot(m1, m2))

# 7. Slicing
slice_example = a[0:2]
print("Slice:", slice_example)


1D Array: [1 2 3]
2D Array:
 [[1 2]
 [3 4]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random Array:
 [[0.20866079 0.37511059 0.84726813]
 [0.46156008 0.08849235 0.10233031]]
Addition: [11 22 33]
Multiplication: [10 40 90]
Square Root: [3.16227766 4.47213595 5.47722558]
Broadcasting Example: [15 25 35]
Mean: 20.0
Sum: 60
Dot Product:
 [[19 22]
 [43 50]]
Slice: [10 20]
